<a href="https://colab.research.google.com/github/NjeriMarion/100DaysOfCode/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#passing a list into the numpy array method so as to create an ndarray
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
print(np.__version__)

1.22.4


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
# Passsing a tuple into the numpy array mehtod so as to create an ndarray.

arr_two = np.array((1,2,3,4,5,6,7))
print(arr_two)

[1 2 3 4 5 6 7]


In [ ]:
#O-D ARRAYS
#0-D or scalars are the elements in an array. Each value in an array is a 0-D array
# i.e
arr_0D = np.array(42)
print(arr_0D)


42


In [ ]:
#1-D ARRAYS
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
#i.e
arr_1D = np.array([1,2,3,4,5])
print(arr_1D)


[1 2 3 4 5]


In [ ]:
#2-D ARRAYS
#An array that has 1-D arrays as its elements is called a 2-D array.
#i.e
arr_2D = np.array([[1,2,3,4,5], [6,7,8,9,10,11]])
print(arr_2D)

[list([1, 2, 3, 4, 5]) list([6, 7, 8, 9, 10, 11])]


<ipython-input-12-5cdf52e5b2f5>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr_2D = np.array([[1,2,3,4,5], [6,7,8,9,10,11]])


In [ ]:
#Specifying the dtype of the array object when creating the ndarray helps removing the deprecation from the ndarray
x= np.array([[1,2,3],[4,5,6]], np.int32)
type(x)
x.shape
x.dtype
print(x, x.shape, x.dtype)

#indexing to get individual elements
y = x[:,2]
y
y[0] = 9 #changes the value at this position in y as well as in x
y
x
print(x.ndim)

#When creating an array, one can define the number of dimensions by using the ndmin argument
z = np.array([1,2,3,4,6], ndmin = 5)
print(z)
print('number of dimensions : ', z.ndim)




[[1 2 3]
 [4 5 6]] (2, 3) int32
2
[[[[[1 2 3 4 6]]]]]
number of dimensions :  5
